apiVersion: apps/v1
kind: Deployment
metadata:
  name: netlogo-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netlogo-website
  template:
    metadata:
      labels:
        app: netlogo-website
    spec:
      containers:
      - name: app
        image: coloshword/netlogo-website:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: netlogo-website
spec:
  type: NodePort
  selector:
    app: netlogo-website
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000 