name: Deploy Astro to GitHub Pages

on:


  push:
    branches:
      - master
      - deployment-test-branch
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Directus build trigger'
  repository_dispatch:
    types: [build_trigger]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Ensure you use a compatible version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

        env:
          DIRECTUS_URL: ${{ secrets.DIRECTUS_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
